INSERT INTO DispatchList
           (DLID
           ,cDLCode
           ,cVouchType
           ,cSTCode
           ,dDate
           ,cRdCode
           ,cDepCode
           ,cPersonCode
           ,SBVID
           ,cSBVCode
           ,cSOCode
           ,cCusCode
           ,cPayCode
           ,cSCCode
           ,cShipAddress
           ,cexch_name
           ,iExchRate
           ,iTaxRate
           ,bFirst
           ,bReturnFlag
           ,bSettleAll
           ,cVerifier
           ,cMaker
           ,iNetLock
           ,iSale
           ,iVTid
           ,cBusType
           ,cCloser
           ,cAccounter
           ,cCreChpName
           ,bIAFirst
           ,ioutgolden
           ,cgatheringplan
           ,dCreditStart
           ,dGatheringDate
           ,icreditdays
           ,bCredit
           ,caddcode
           ,iverifystate
           ,ireturncount
           ,iswfcontrolled
           ,icreditstate
           ,bARFirst
           ,cmodifier
           ,dmoddate
           ,dverifydate
           ,ccusperson
           ,dcreatesystime
           ,dverifysystime
           ,dmodifysystime
           ,csvouchtype
           ,iflowid
           ,bsigncreate
           ,bcashsale
           ,cgathingcode
           ,cChanger
           ,cChangeMemo
           ,outid
           ,bmustbook
           ,cBookDepcode
           ,cBookType
           ,bSaUsed
           ,bneedbill
           ,baccswitchflag
           ,iPrintCount
           ,ccuspersoncode
           ,cSourceCode
           ,bsaleoutcreatebill
           ,cSysBarCode
           ,cCurrentAuditor
           ,csscode
           ,cinvoicecompany
           ,fEBweight
           ,cEBweightUnit
           ,cEBExpressCode
           ,iEBExpressCoID
           ,SeparateID
           ,bNotToGoldTax
           ,cEBTrnumber
           ,cEBBuyer
           ,cEBBuyerNote
           ,ccontactname
           ,cEBprovince
           ,cEBcity
           ,cEBdistrict
           ,cmobilephone
           ,cInvoiceCusName
           ,cweighter
           ,dweighttime
           ,cPickVouchCode])
     VALUES
           ((select top 1 max(maxorderid) from YDH_Max_OrderID where TableName = 'DISPATCH')
           ,#orderNum#
           ,'05'
           ,'01'
           ,CONVERT(char,#createTime#,23)
           ,NULL
           ,'24'
           ,'0211'
           ,0
           ,NULL
           ,#originOrderNum#
           ,#customer.code#
           ,NULL
           ,NULL
           ,NULL
           ,'人民币'
           ,1
           ,17
           ,0
           ,1
           ,0
           ,NULL
           ,'易订货'
           ,NULL
           ,0
           ,75
           ,'普通销售'
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,NULL
           ,2
           ,NULL
           ,1
           ,NULL
           ,0
           ,NULL
           ,NULL
           ,CONVERT(char,#createTime#,23)
           ,NULL
           ,CONVERT(char,#createTime#,23)
           ,CONVERT(char,#createTime#,23)
           ,NULL
           ,NULL
           ,0
           ,0
           ,0
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,0
           ,NULL
           ,NULL
           ,NULL
           ,1
           ,'||SA03|'+#orderNum#
           ,NULL
           ,NULL
           ,#customer.code#
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL)